theme: jekyll-theme-architect
name: r00t3r ( pronounced rooter )
description: Cyber Security and Machine Learning Enthusiast
avatar: https://github.com/r00t3r-god/r00t3r-god.github.io/blob/main/avatar.jpg
